##Installation of Deseq2
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install()
# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("DESeq2")
lilbrary("readxl")
library (DeSeq2)
setwd('/Volumes/WD1/Desktop/laboratory files/Results/Altria project/DEGlist')
readscount<-read.excel('/Volumes/WD1/Desktop/laboratory files/Results/Altria project/DEGlist/raw data_readcount.xlsx')
colData <- read.excel('/Volumes/WD1/Desktop/laboratory files/Results/Altria project/DEGlist/colData.xlsx')
condition<-factor(c("Mock", "Flag22","Pnic", "Flag22+Pnic"))
timepoint <- factor(c("T1","T2","T3","T4","T5","T6", "T7"))
replicate <- factor(c("One", "Two", "Three", "Four"))
colData
head(readscount)
